### ISSUE TITLE
JVM transform task fails on kotlinx.coroutines

### ISSUE THREAD

**Issue by qwwdfsad** [Kotlin/kotlinx.atomicfu#112]
Execution failed for task ':kotlinx-coroutines-core:transformJvmMainAtomicfu'.
> java.lang.ClassNotFoundException: kotlinx.coroutines.EventLoopImplBase$DelayedTaskQueue

Stacktrace:
```
Caused by: java.lang.ClassNotFoundException: kotlinx.coroutines.EventLoopImplBase$DelayedTaskQueue
        at kotlinx.atomicfu.transformer.AtomicFUTransformer$CW.getCommonSuperClass(AtomicFUTransformer.kt:1165)
        at org.objectweb.asm.SymbolTable.addMergedType(SymbolTable.java:1200)
        at org.objectweb.asm.Frame.merge(Frame.java:1299)
        at org.objectweb.asm.Frame.merge(Frame.java:1244)
        at org.objectweb.asm.MethodWriter.computeAllFrames(MethodWriter.java:1610)
        at org.objectweb.asm.MethodWriter.visitMaxs(MethodWriter.java:1546)
        at org.objectweb.asm.tree.MethodNode.accept(MethodNode.java:767)
        at kotlinx.atomicfu.transformer.AtomicFUTransformer$TransformerMV.visitEnd(AtomicFUTransformer.kt:610)
        at org.objectweb.asm.ClassReader.readMethod(ClassReader.java:1288)
        at org.objectweb.asm.ClassReader.accept(ClassReader.java:688)
        at org.objectweb.asm.ClassReader.accept(ClassReader.java:400)
        at kotlinx.atomicfu.transformer.AtomicFUTransformer.transformFile(AtomicFUTransformer.kt:237)
        at kotlinx.atomicfu.transformer.AtomicFUTransformer.transform(AtomicFUTransformer.kt:172)
        at kotlinx.atomicfu.plugin.gradle.AtomicFUTransformTask.transform(AtomicFUGradlePlugin.kt:406)
        at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:103)

```

**Comment by elizarov** [comment]
Fixed by PR #110 in version `0.14.1`
