### ISSUE TITLE
Transformation failure in objects

### ISSUE THREAD

**Issue by ReneeVandervelde** [Kotlin/kotlinx.atomicfu#118]
`getAndUpdate` Seems to fail when the parent class is an object:

```kotlin
object Example {
    private val atomic = atomic("test")

    fun update() {
        atomic.getAndUpdate { "$it !" }
    }
}
```

Results in the following compilation error:
```
Failed to transform: java.lang.ArrayIndexOutOfBoundsException: -1
java.lang.ArrayIndexOutOfBoundsException: -1
        at org.objectweb.asm.Frame.getConcreteOutputType(Frame.java:1139)
        at org.objectweb.asm.Frame.merge(Frame.java:1184)
        at org.objectweb.asm.MethodWriter.computeAllFrames(MethodWriter.java:1610)
        at org.objectweb.asm.MethodWriter.visitMaxs(MethodWriter.java:1546)
        at org.objectweb.asm.tree.MethodNode.accept(MethodNode.java:767)
        at kotlinx.atomicfu.transformer.AtomicFUTransformer$TransformerMV.visitEnd(AtomicFUTransformer.kt:616)
        at org.objectweb.asm.ClassReader.readMethod(ClassReader.java:1288)
        at org.objectweb.asm.ClassReader.accept(ClassReader.java:688)
        at org.objectweb.asm.ClassReader.accept(ClassReader.java:400)
        at kotlinx.atomicfu.transformer.AtomicFUTransformer.transformFile(AtomicFUTransformer.kt:238)
        at kotlinx.atomicfu.transformer.AtomicFUTransformer.transform(AtomicFUTransformer.kt:172)
        at kotlinx.atomicfu.plugin.gradle.AtomicFUTransformTask.transform(AtomicFUGradlePlugin.kt:406)
```

Changing the declaration to `class` will compile successfully.

This seems to have been reported before in #94 as a problem with companion objects, which was closed but never resolved.

Kotlin Version: 1.3.61
atomicfu version: 0.14.1

**Comment by LikhanovMaxim** [comment]
Hi, 
I have the same error with a bit another code:
```
private val top = atomic<Int?>(null)

fun main() {
    top.update { 0 }
    println()
}
```
Error log: [error_atomic.txt](https://github.com/Kotlin/kotlinx.atomicfu/files/4385472/error_atomic.txt)
kotlinVersion=1.3.70
atomicFuVersion=0.14.2
