### ISSUE TITLE
Execution failed for task ':transformAtomicfuClasses'. NestHost requires ASM7

### ISSUE THREAD

**Issue by akhsaul** [Kotlin/kotlinx.atomicfu#199]
```
plugins {
    kotlin("jvm") version "1.5.30"
    java
}

buildscript {
    dependencies {
        classpath("org.jetbrains.kotlinx:atomicfu-gradle-plugin:0.16.3")
    }
}
apply(plugin = "kotlinx-atomicfu")

group = "org.akhsaul"
version = "1.0-SNAPSHOT"
java.targetCompatibility = JavaVersion.VERSION_15
val kotlinVersion = "1.5.30"
val okhttp3Version = "5.0.0-alpha.2"
val coroutineVersion = "1.5.1-native-mt"

repositories {
    google()
    mavenCentral()
    gradlePluginPortal()
    maven {
        isAllowInsecureProtocol = true
        url = uri("http://4thline.org/m2")
    }
    maven {
        url = uri("https://jitpack.io")
    }
}

dependencies {
    implementation("org.jetbrains.kotlin:kotlin-stdlib:$kotlinVersion")
    implementation("org.jetbrains.kotlinx:kotlinx-coroutines-core:$coroutineVersion")
    implementation("com.squareup.okhttp3:okhttp:$okhttp3Version")
    implementation("com.squareup.okhttp3:logging-interceptor:$okhttp3Version")
    implementation("com.squareup.okhttp3:okhttp-urlconnection:$okhttp3Version")
    implementation("com.squareup.okhttp3:okhttp-dnsoverhttps:$okhttp3Version")
    implementation("com.fasterxml.jackson.module:jackson-module-kotlin:2.13.+")
    implementation("commons-io:commons-io:2.11.0")
    testImplementation("org.jetbrains.kotlin:kotlin-test-junit5:$kotlinVersion")
    testImplementation("org.junit.jupiter:junit-jupiter-api:5.7.2")
    testRuntimeOnly("org.junit.jupiter:junit-jupiter-engine:5.7.2")
}

tasks.withType<org.jetbrains.kotlin.gradle.tasks.KotlinCompile>().configureEach {
    kotlinOptions {
        freeCompilerArgs = listOf(
            "-Xjsr305=strict",
            "-Xextended-compiler-checks"
        )
        jvmTarget = "15"
    }
    kotlin.sourceSets.all {
        languageSettings {
            optIn("kotlin.Experimental")
            optIn("kotlin.ExperimentalStdlibApi")
            optIn("kotlin.io.path.ExperimentalPathApi")
            optIn("kotlin.contracts.ExperimentalContracts")
            optIn("kotlin.RequiresOptIn")
        }
    }
}

tasks.withType<Test> {
    useJUnitPlatform()
}
```

when i try `Executing task 'build'`, gradle throw error:

```
14:17:43: Executing task 'build'...

> Task :compileKotlin UP-TO-DATE
> Task :compileJava UP-TO-DATE
> Task :processResources UP-TO-DATE
> Task :classes UP-TO-DATE
> Task :transformAtomicfuClasses FAILED
4 actionable tasks: 1 executed, 3 up-to-date

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':transformAtomicfuClasses'.
> NestHost requires ASM7

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 459ms
14:17:44: Task execution finished 'build'.
```

**Comment by mvicsokolova** [comment]
The problem is that for transformation atomicfu creates `ClassVisitor` instance passing `ASM5` as the minimal api version of ASM. And while traversing the generated bytecode (targeting Java 15) this `ClassVisitor` invokes `ClassVisitor.visitNestHost` which requires the minimal `ASM7` api version of ASM.
I guess, we should consider updating the minimal ASM version passed to the ClassVisitor constructor.

**Comment by lion7** [comment]
I just encountered more or less the same error when using `atomicfu` in a project that includes a JPMS module descriptor.
ASM is unable to process the `module-info.class` file and fails with this exception:
```

Caused by: java.lang.UnsupportedOperationException: Module requires ASM6
	at org.objectweb.asm.ClassVisitor.visitModule(ClassVisitor.java:145)
	at org.objectweb.asm.ClassReader.readModuleAttributes(ClassReader.java:758)
	at org.objectweb.asm.ClassReader.accept(ClassReader.java:557)
	at org.objectweb.asm.ClassReader.accept(ClassReader.java:401)
	at kotlinx.atomicfu.transformer.AtomicFUTransformer.analyzeFileForFields(AtomicFUTransformer.kt:234)
	at kotlinx.atomicfu.transformer.AtomicFUTransformer.analyzeFilesForFields(AtomicFUTransformer.kt:227)
	at kotlinx.atomicfu.transformer.AtomicFUTransformer.transform(AtomicFUTransformer.kt:196)
	at kotlinx.atomicfu.plugin.gradle.AtomicFUTransformTask.transform(AtomicFUGradlePlugin.kt:427)
	at jdk.internal.reflect.GeneratedMethodAccessor654.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:104)
        ...truncated...


* Get more help at https://help.gradle.org

BUILD FAILED in 2s
09:22:53: Task execution finished 'assemble --stacktrace'.
```
