### ISSUE TITLE
Gradle transformJvmMainAtomicfu failed when using atomic() in companion obj

### ISSUE THREAD

**Issue by Him188** [Kotlin/kotlinx.atomicfu#94]
```
Caused by: java.lang.ArrayIndexOutOfBoundsException: Index -1 out of bounds for length 0
        at org.objectweb.asm.Frame.a(Unknown Source)
        at org.objectweb.asm.MethodWriter.visitMaxs(Unknown Source)
        at org.objectweb.asm.tree.MethodNode.accept(Unknown Source)
        at kotlinx.atomicfu.transformer.AtomicFUTransformer$TransformerMV.visitEnd(AtomicFUTransformer.kt:611)
        at org.objectweb.asm.ClassReader.b(Unknown Source)
        at org.objectweb.asm.ClassReader.accept(Unknown Source)
        at org.objectweb.asm.ClassReader.accept(Unknown Source)
        at kotlinx.atomicfu.transformer.AtomicFUTransformer.transformFile(AtomicFUTransformer.kt:237)
        at kotlinx.atomicfu.transformer.AtomicFUTransformer.transform(AtomicFUTransformer.kt:172)
        at kotlinx.atomicfu.plugin.gradle.AtomicFUTransformTask.transform(AtomicFUGradlePlugin.kt:387)

```

This works fine
```kotlin
class Bot( ... ) {
    private val count = atomic<Int>(0)

    val id = count.getAndUpdate { it + 1 }
}
```

But this doesn't work
```kotlin
class Bot( ... ){
    val id = count.getAndUpdate { it + 1 }

    companion object {
      private val count = atomic<Int>(0)
    }
}
```
And after I removed `private`, I got a new exception `Unsupported return within atomic operation`

**Comment by Him188** [comment]
Exceptions are the same when using `atomic(0)` instead of `atomic<Int>(0)`

**Comment by elizarov** [comment]
Have you found a workaround or an issue was resolved?

**Comment by Him188** [comment]
@elizarov No.

**Comment by Him188** [comment]
It might because `count` is private in the `companion`, accessing it from outside the `companion object` produces that issue.

I added a new fun to do `getAndIncrease` in the `companion`, which works well
```kotlin
companion object{
private val count = atomic(0)
fun nextCount() = count.getAndIncrease()
```
